/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2b63a8c7-062d-436a-a03f-284131b09b3b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yTWRjgD2c",
    "aws_user_pools_web_client_id": "7ri90o861263e5f935th7eb7r",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://uiyr5ud6ifevlfozciyizfiy4m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "HackathonLectureDB-dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "lecture-summary-output172043-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
