/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://w6rp6lgcpfgsdjkxv5xgwuoh6a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ytuwt7zeendujetrm7mhn4a64a",
    "aws_cognito_identity_pool_id": "us-east-1:0c08fe62-547b-457b-9d21-616a36059313",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hsBdBWEfh",
    "aws_user_pools_web_client_id": "7c7ih7fitjjaifs5qme3hvhh5o",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_output_files_s3_bucket":
        "lecture-summary-output-993839318285",

    "aws_user_files_s3_bucket_region":
        "us-east-1",

    "aws_dynamodb_all_tables_region":
        "us-east-1",
    "aws_dynamodb_table_schemas": [

        {

            "tableName":
                "HackathonLectureSummary",

            "region":
                "us-east-1"

        }

    ]

};


export default awsmobile;
