/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://xwoznfkdczejpmodt3zcgz3mdy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-west-2:6152f07c-9e17-47b5-8a2b-ae1d807c852e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ycZWNH0KC",
    "aws_user_pools_web_client_id": "42h0b9d3e71b7pp6galf2c57j0",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "HackathonLectureDB-main",
            "region": "us-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "scotth-outputs-genaihackathon23",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
